### PR TITLE
Add hide check to write_arg_markdown

### PR DESCRIPTION
**Pull request by wackazong**
Hidden arguments are now correctly filtered out from the markdown documentation.

### CODE REVIEW

**Comment by ilyagr** [comment]
This PR includes a lot of unrelated changes. I think only the snippet

```
    // Don't document commands marked with `clap(hide = true)`.
    if arg.is_hide_set() {
        return Ok(());
    }
```

is relevant.

I am not the maintainer, but I think that, to make this mergeable, you should get rid of all the unrelated stuff and change one of the tests to have a hidden argument.

@ConnorGray , I'm happy to do that myself if it helps and if you are planning to release any future versions.

**Comment by wackazong** [comment]
@ilyagr your are absolutely right, I accidentally pushed more changes to this PR. Only the first commit is relevant. And I agree with you regarding the test as well. Thanks for the input.

**Comment by ilyagr** [comment]
I put a cleaned-up version of this with tests in https://github.com/ConnorGray/clap-markdown/pull/22, specifically https://github.com/ConnorGray/clap-markdown/pull/22/commits/48907e15d4fcaf405ff554b40ce1d6526b9631c1. My approach is a little different, note the test of a command that *only* has hidden options.

**Comment by ConnorGray** [comment]
@wackazong @ilyagr Thank you both for your contributions to this library, and please accept my apologies for the delay in processing PRs in this repo😌 

I agree with @ilyagr this is a bit large to merge in one go, but I've merged the piece Ilya broke out in #22; if there are other parts of this PR you'd like to see get merged, I'm happy to discuss them in a new PR 🙂

**Pull request closed without merging**
